site_name: Mortal Kombat 1 Modding Docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - navigation.footer
      
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
        position: header
        
repo_url: https://github.com/MK1-Modding/UBLScripts
repo_name: UBLScripts

plugins:
  - search
  - social

nav:
  - Home: index.md
  - Getting started:
      - Setting up modding environment: getting-started/introduction.md
      - Installation: getting-started/installation.md
      - Fixing common issues:
            - Body deformations in poses: getting-started/common-issues/body-deforms/body-deforms.md
  - UBL Framework:
      - Overview: ubl/ubl-overview.md
      - Installation: ubl/ubl-install-guide.md
      - Using UBL in your mods: ubl/ubl-usage-guide.md
      - Events:
            - Events Overview: ubl/events/events-overview.md
            - LoadAssets: ubl/events/LoadAssets/LoadAssets.md
            - Mesh related:
                    - ChangeFace: ubl/events/Mesh/ChangeFace/ChangeFace.md
                    - ChangeBody: ubl/events/Mesh/ChangeBody/ChangeBody.md
                    - ChangeHair: ubl/events/Mesh/ChangeHair/ChangeHair.md
                    - ChangeCloth: ubl/events/Mesh/ChangeCloth/ChangeCloth.md
            - Gear related:
                    - ChangeGearMask: ubl/events/Gear/ChangeGearMask/ChangeGearMask.md
                    - ChangeGearCowl: ubl/events/Gear/ChangeGearCowl/ChangeGearCowl.md
            - Material related:
                    - ChangeFaceOverrideMaterials: ubl/events/OverrideMats/ChangeFaceOverrideMaterials/ChangeFaceOverrideMaterials.md
                    - ChangeBodyOverrideMaterials: ubl/events/OverrideMats/ChangeBodyOverrideMaterials/ChangeBodyOverrideMaterials.md
                    - ChangeHairOverrideMaterials: ubl/events/OverrideMats/ChangeHairOverrideMaterials/ChangeHairOverrideMaterials.md
                    - ChangeClothOverrideMaterials: ubl/events/OverrideMats/ChangeClothOverrideMaterials/ChangeClothOverrideMaterials.md
            - Sound related:
                    - ChangeGrunts: ubl/events/Sounds/ChangeGrunts/ChangeGrunts.md
                    - ChangeVoice: ubl/events/Sounds/ChangeVoice/ChangeVoice.md
            - Miscellaneous:
                    - ChangeBlood: ubl/events/Miscellaneous/ChangeBlood/ChangeBlood.md
                    - ChangeSkinFX: ubl/events/Miscellaneous/ChangeSkinFX/ChangeSkinFX.md
                    - ChangeMoveset: ubl/events/Miscellaneous/ChangeMoveset/ChangeMoveset.md
                    
  - FAQ: faq.md
  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.mark
  - attr_list